spring:
  config:
    activate:
      on-profile: dev
  main:
    web-application-type: none
    application:
    name: page_path_web

datax:
  sync:
    hdfs-default-fs: hdfs://10.10.0.107:8020/
    # be streamLoad url
    doris-load-url: 10.10.0.112:18040
    debug: true
    datax-python-path: python3 /data/datax/bin/datax.py
    target-data-source:
      dbtype: 1
      jdbc-url: jdbc:impala://10.10.0.106:21050/ods;AuthMech=0;
      username: admin
      password: admin
      driver-class-name: com.cloudera.impala.jdbc41.Driver
logging:
  level:
    com.datax.sync: DEBUG
    org.mongodb.driver: ERROR
    # 或者完全关闭
    org.mongodb.driver.cluster: OFF
    org.mongodb.driver.connection: OFF
  pattern:
    console: "%msg%n"